### PR TITLE
CM-264 / Jenkins Clean-Up Artifactory FAILED

### PR DESCRIPTION
**Pull request by apgsga-jhe**
Der Title des Tickets ist eigentlich falsch, das passiert nicht während Clean-up, sondern während Patch Ablauf.

Wie im Ticket geschrieben, ganz einfach Anpassungen um den "Return-Value" zu loggen ...

Es wurde auf jenkins-t richtig getestet ...

### CODE REVIEW

**Comment by chhex** [comment]
@apgsga-jhe I am not quite sure what your expectations are here? The execution of the Gradle process either fails or succeeds.

**Comment by chhex** [comment]
@apgsga-jhe I got it , you want to log the standard output?

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe I am not quite sure what your expectations are here? The execution of the Gradle process either fails or succeeds. Is it that what you want to see?

@chhex : There are situations where it fails because Artifactory is not available (or at least, we can't reach it). In this particular situation, we would like to wait couple of seconds, and retry .... The problem is I'm not sure what exact message we get back in that situation. In a first step, I would like to log it, wait for the problem to re-occur, and eventually adapt the pipeline accordingly,based on this returned value.

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe I got it , you want to log the standard output?

@chhex : yep

**Comment by chhex** [comment]
> > @apgsga-jhe I am not quite sure what your expectations are here? The execution of the Gradle process either fails or succeeds. Is it that what you want to see?
> 
> @chhex : There are situations where it fails because Artifactory is not available (or at least, we can't reach it). In this particular situation, we would like to wait couple of seconds, and retry .... The problem is I'm not sure what exact message we get back in that situation. In a first step, I would like to log it, wait for the problem to re-occur, and eventually adapt the pipeline accordingly,based on this returned value.

@apgsga-jhe  What fails? The publish? 
And i am not sure, what you mean with message we get back? Basically Gradle builds do not return anything
And you that you can turn on gradle logging level with the runtime parameter  --info or --debug for example and also in case of exceptions ask for a --stacktrace? 
And retrying should to me like a very last resort ..... if we really need a retry i would see that we eliminate the contingency 
Just my fives cents

**Comment by chhex** [comment]
Example File based Repo for Patches

Publishing: 
`publishing {
    publications {
        myLibrary(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = 'patchRepo'
            url = "file://${whatever}/patch"
        }
    }
}`

Dependency Resolution
`repositories {
    maven {
        url "file://${whatever}/patch"
       mavenContent {
            releasesOnly()
        }
    }
   mavenLocal()
   maven { 
	  credentials {
        	username mavenRepoUser
        	password mavenRepoPwd
    	}
	  url "${mavenRepoBaseUrl}/${mavenRepoName}" 
  }
}`

We could restrict this even to ReleaseOnly and keep our remote Repository as last in the search order. 
Naturally the file repository would need to be tightly secured

**Comment by apgsga-jhe** [comment]
> > > @apgsga-jhe I am not quite sure what your expectations are here? The execution of the Gradle process either fails or succeeds. Is it that what you want to see?
> > 
> > 
> > @chhex : There are situations where it fails because Artifactory is not available (or at least, we can't reach it). In this particular situation, we would like to wait couple of seconds, and retry .... The problem is I'm not sure what exact message we get back in that situation. In a first step, I would like to log it, wait for the problem to re-occur, and eventually adapt the pipeline accordingly,based on this returned value.
> 
> @apgsga-jhe I shouldn’t be opinating, since i don‘t really know the whole context 😅
> And i am not sure, what you mean with message we get back? Basically Gradle builds do not return anything... it‘s Jenkins , which is capturing the stdoutput of the gradle build, which quite arbitrary...
> In that context, you know that you can turn on gradle logging level with the runtime parameter --info or --debug for example and also in case of exceptions ask for a --stacktrace?
> Also retrying seems to me like a last resort ..... if we really need a retry on recurring basis , i would see that we eliminate the contingency. If it is the network and we don't have any control, we could use a seperate local file based Maven Repository (additionally to mavenLocal()) containing only the Patch produced version for the Patch Pipelines, which we periodically consolidate against Artifactory, basically uploading what isn't in Artifactory. That would be also much faster probably and probably much more reliable. Maybe something we should target, which de next release.
> 
> Just my fives cents

@chhex : Absolutely, when we'll revise the pipelines in order to integrate our GradlePlugins, it would probably be good to take the opportunity to reduce the traffic to/from Artifactory, it will also help reducing the costs 😆 ....

In the meantime, as a simple workaround, what I would like to be able is to detect the following (which  occured several time already) :

```
:it21-ui-pkg-server:generateDescriptorFileForYumRpmPublication
:it21-ui-pkg-server:publishYumRpmPublicationToYumpatchrepoRepository
Upload https://artifactory4t4apgsga.jfrog.io/artifactory4t4apgsga/yumpatchrepo/apg-jadas-service-CHEI211-7015.6750-1.noarch.rpm
:it21-ui-pkg-server:publishYumRpmPublicationToYumpatchrepoRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':it21-ui-pkg-server:publishYumRpmPublicationToYumpatchrepoRepository'.
> Failed to publish publication 'yumRpm' to repository 'yumpatchrepo'
   > Could not write to resource 'https://artifactory4t4apgsga.jfrog.io/artifactory4t4apgsga/yumpatchrepo/apg-jadas-service-CHEI211-7015.6750-1.noarch.rpm'.
      > artifactory4t4apgsga.jfrog.io:443 failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

I was hoping that the resultOutput from the sh command might return it, but I'm not sure ... reason why I though to first log it as a first step ...

**Comment by chhex** [comment]
@apgsga-jhe  This is a requirement , see https://github.com/gradle/gradle/pull/9163 and https://github.com/gradle/gradle/issues/4629  albeit not a trivial one. 

 I don't think you can without highest complexity , build in "retrying" into the Pipeline / Gradle scripts in Exception Cases. Where would you handle the Exception? In the Gradle script .... almost impossible. In the Pipeline? Where? With every Maven / Gradle Task  that uses a network connection? Ok, you could do that in a generic closure.... but hmmm is that what you really want? That could have quite uncalculated side effects and would need to thoroughly tested. In specific build tasks? We leads to the questions:
Does this happen often? Daily, weekly?  Is only one build script? And only Gradle? 

If the later two: then i would simply put a higher http timeout into the gradle. properties

If not: Why not use the redo? I would in that case go until we come with release 2 , for the apscli.sh redo feature. If if this needs some more testing, i think that is exactly what we wanted that feature for. You could even automate it to an extent.

**Comment by apgsga-jhe** [comment]
Hi @chhex ,

Thanks for the different inputs.

Yep exactly, I found as well on "Gradle-Jira" that they're having tickets in order to eventually implement a retry mechanism.

Yep, if I would do that, it would be for all places where we call gradle tasks for our bundle project, because we've seen this problem only (I believe) with these tasks. What I would built would be as dummy as (in pseudo-code):

```
def retry = 0
def out = "gradlew bundle"
while(out.contains(":443 failed to respond") && retry < 5) {
  out = "gradlew bundle"
  retry++;
}
```

... but ok, not sure it would work, because not sure what we get back when it fails. And agreed, also not 100% sure of the side-effects.

To the question if it happens often ... No not really, but when it does, naturally really annoying ;) ;) .... because it can be that a patch hasn't been installed in PROD, or the onClone chain failed (ok ok .... the cloning part will be revisited :) )

It has been a long time since we didn't use the "redo". However the last time we did, we actually put a patch in production, which wasn't our aim :). We obviously made something wrong (or was something wrong in the JSON file), but I must say I'm a bit scared to give a new try when the next status for a patch is "production". But yep of course, we also have an option there.

Yep, for now the 2 parameters are set to 30sec, we could probably triple them. I had the feeling that the problem wasn't related with these timeouts, but really not sure. And it probably won't hurt anything if we increase them.

@apgsga-stb , @apgsga-uge , FYI

**Comment by chhex** [comment]
@apgsga-jhe @apgsga-stb @apgsga-uge 

To make the long story short:
-  i don‘nt think adressing a „problem“, without knowing the cause, with a retry of the gradle build enhances the reliability of the builds, to say the least
- if the problem only occurs with gradle builds , there is high probability that is a problem wthin the gradle stack
- I would first identify precisely from where the exception comes in the gradle call stack. You can see the exception stacktrace with the gradle option —stacktrace and then take it from there. 
- And yes naturely, the redo should be tested thoroughly. But i still think, this use case is precisely what it is intended for

**Comment by apgsga-jhe** [comment]
@chhex : Thanks for the inputs in this one. Yep, I'll go ahead with a "--stacktrace" where I feel the issue could happen. Cheers!

**Pull request merged**
