### PR TITLE
JAVA8MIG-504 onDemand Pipeline installed on wrong target

### PR DESCRIPTION
**Pull request by chhex**
The problem: 

The field installationTarget was used in "conflicting" ways
As Installation Target for OnDemandPipeline from the UI 
Internally as single reference from PatchConfig for the currentTarget being processed. 

With the redo, which saves the PatchConfig State before and after a Stage, this could lead to fact , that the installationTarget is overwritten from the Prod Pipeline.

Solution -> The single Reference in PatchConfig for the currentTarget being processed is renamed to currentTarget.

### CODE REVIEW

**Comment by chhex** [comment]
@apgsga-jhe  you can merge, when you are ready to test with @apgsga-uge

**Comment by apgsga-jhe** [comment]
@chhex : to be 100% sure since we introduced now the 1.0.x release. What I'll do is:

1. Merge this pull request.
2. Tag the result with "v1.0.1.RELEASE"
3. Change the value of the GITHUB_JENKINS_VERSION_TAG accordingly.

Do you agree? Or did I miss any step?

**Comment by chhex** [comment]
@apgsga-uge  If you think, that the change merits a Release, yes, 
See also   https://github.com/apgsga-it/jenkins-patch-scripts/releases

But i thinks it's really  more a bug fix of the current Release. An since each commit is tracked in Github i don't  really see a problem.

What do you think?

**Comment by apgsga-jhe** [comment]
@chhex : No I don't believe this merits a new Release. However I wasn't sure if I'll be able to override an existing Tag (maybe I need to delete it, and re-tag).

**Comment by chhex** [comment]
@apgsga-uge  @apgsga-jhe  I would'nt even tag it. We have a release tag. For what? As said we can differentiate between commits.

**Comment by apgsga-jhe** [comment]
@chhex : I believe we need to tag because of this one: https://jenkins.apgsga.ch/view/PatchUtils/job/reinstallPatchAfterClone/configure

**Comment by chhex** [comment]
@apgsga-uge " I believe we need to tag because of this one: https://jenkins.apgsga.ch/view/PatchUtils/job/reinstallPatchAfterClone/configure" Why exactly? To identify the change? To be able to rollback? 
We can do both much easier and less error prone with the pull reqeust

**Comment by chhex** [comment]
@apgsga-uge  Did you look at the changes https://github.com/apgsga-it/jenkins-patch-scripts/pull/31/files ? 
It's basically renaming patchConfig.installationTarget to patchConfig.currentTarget

**Comment by chhex** [comment]
@apgsga-uge  @apgsga-jhe  That a look a other Github projects. They done dump the Version / Release with each commit on a Release Branch: 
https://github.com/chhex/java-client-api
https://github.com/spring-projects/spring-boot
etc

**Comment by apgsga-jhe** [comment]
@chhex : no problem ;) ... Mmh, I'm in the train already, without a headset ... But I was referring to the above project because of the "Branch Specifier" Property which is set to "refs/tags/${GITHUB_JENKINS_VERSION_TAG}"

**Comment by chhex** [comment]
@apgsga-jhe  Ich would simply merge. We are not even in Produktion yet. Until then i would simply bug fixes.

**Comment by apgsga-jhe** [comment]
Agreed. I'll merge and then re-tag with "v1.0.0.RELEASE".

**Pull request merged**
